### ISSUE TITLE
JPG/JPW buttons not becoming active in Safari

### ISSUE THREAD

**Issue by oobrien** [oobrien/oomap#38] opened 2019-09-10 11:10 UTC
These should become active once Save and Generate PDF is clicked but reports that they are not, in Safari (works in Chrome).

**Comment by oobrien** [comment] 2019-09-10 11:12
Works for me in Safari...

**Comment by cadnant** [comment] 2023-07-22 09:58
Closing as unable to reproduce.

**Closed by cadnant** 2023-07-22 09:58 UTC
Labels: bug
