### ISSUE TITLE
PDFs do not include openstreetmap data - Global Edition

### ISSUE THREAD

**Issue by peterblyton** [oobrien/oomap#32] opened 2018-04-02 09:08 UTC
In Global Edition - map creation all works correctly as normal. However, the PDF produced does not include the Openstreetmap data. See attached map as example (5ac1f1d8c8b29).

[oom5ac1f1d8c8b29.pdf](https://github.com/oobrien/oomap/files/1867687/oom5ac1f1d8c8b29.pdf)

**Comment by rugk** [comment] 2018-04-02 15:00
Cannot reproduce. Works for me.

**Comment by peterblyton** [comment] 2018-04-08 10:25
Can you reproduce this issue if you load up map "5ac1f1d8c8b29", and create the PDF? I have checked a couple of different web browsers, and I can still reproduce a blank map (only controls are shown).

Interestingly, if I re-create a map from scratch, it seems to work fine.

**Comment by rugk** [comment] 2018-04-08 12:36
Indeed, I can reproduce it with `5ac1f1d8c8b29`. I tried to create maps at other places in new Zealand and Australia, Philippines, China, Russia, Euope etc. and it did not work afterwards,
But maybe I just got rate-limited somehow??

**Comment by oobrien** [comment] 2018-05-12 20:48
I haven't pinned this issue down yet, but I think it may be something to do with the longitude being less than -180 degrees.

**Comment by oobrien** [comment] 2018-05-12 23:57
This should now be fixed with https://github.com/oobrien/oomap/commit/fd24ae45ca44cd3a2d314f036864568392fe3cfd - unfortunately already saved maps such as the one above will not load correctly (but then the background map never loaded correctly in their PDFs anyway). It affects all maps where the longitude was less than -180 degrees or more than +180 degrees, caused by OpenLayers not adjusting the longitude as the dateline is panned across.

**Closed by oobrien** 2018-05-12 23:57 UTC
